combat-bypass-permission: "antylogout.bypass"
combat-duration: 20
combat-message:
    type: ACTION_BAR
    content: "&4&lAntylogout &8&l| &c{time}"
combat-end-message:
    - type: ACTION_BAR
      content: "Twoja walka dobiegla konca"
    - type: CHAT
      content: "Twoja walka dobiegla konca"
combat-start-notifications-enabled: true
combat-start-message-attacker:
    type: CHAT
    content: "Rozpoczynasz walke z {victim}"
combat-start-message-victim:
    type: CHAT
    content: "Zostales zaatakowany/a przez {attacker}. Jestes teraz w walce!"
remove-combat-on-opponent-death: true
remove-combat-message:
    type: CHAT
    content: "Twoj oponent {opponent} zginal. Twoja walka sie konczy!"
combat-from-mobs: true
combat-from-projectiles: true
commands-blocked-during-combat: true
combat-command-whitelist: ["msg", "r", "reply"]
combat-command-blocked-message:
    type: TITLE
    content: "&c&l✖ \n &7Nie mozesz uzyc komendy &f&n{command}&r&7 podczas walki!"
combat-blocked-regions: ["spawn"]
combat-blocked-region-knockback-multiplier: 1
combat-blocked-region-enter-message:
    type: CHAT
    content: "&c&l✖ &8&l| &7Nie mozesz wejsc na &fteren&7 regionu &f&n{region}&r&7 podczas walki!"